version: '3'
services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      # - MONGODB_USERNAME=root
      # - MONGODB_PASSWORD=agiIJHbsGA6Pdymq
      # - MONGODB_DATABASE=selmanCoyotiv
      - MONGODB_CONNECTION_STRING=mongodb://mongo/homemade-meal
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./backend/src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
